arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.005
  goal_orientation_tolerance: 0.01