gazebo_ros_control:
    pid_gains:
      joint1:  # 关节名称，必须与 URDF 中的关节名一致
        p: 100.0  # P 增益（比例增益，必须设置）
        i: 0.0    # I 增益（积分增益，可选，默认 0）
        d: 10.0   # D 增益（微分增益，可选，默认 0）
      joint2:
        p: 100.0
        i: 0.0
        d: 10.0
      joint3:
        p: 100.0
        i: 0.0
        d: 10.0
      joint4:
        p: 100.0
        i: 0.0
        d: 10.0
      joint5:   # 添加joint5的PID增益
        p: 100.0
        i: 0.0
        d: 10.0
      joint6:   # 添加joint6的PID增益
        p: 100.0
        i: 0.0
        d: 10.0