controller_list:
  - name: fake_all_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_end_efffector_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint5
      - joint6
initial:  # Define initial robot poses per group
  - group: all_arm_group
    pose: init_pose