# controller_list:
#   - name: all_arm_group_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - joint1
#       - joint2
#       - joint3
#       - joint4
#   - name: end_efffector_group_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - joint5
#       - joint6